### ISSUE TITLE
Unable to Change the Adapter

### ISSUE THREAD

**Issue by navinks04** [8bitgeek/OpenNIC-Wizard#2]
The wizard dynamically changes the DNS for Local Area Connection but doesnt seem to change the DNS for Wireless Network Connection. Please advise. Tried google about the issue but no there were no posts about such issue.

**Comment by 8bitgeek** [comment]
Presumably you are on Windows(tm)? I no longer have a Windows(tm) computer other than in a VM but it does not have wireless. In any case, it would this funtion here that is the area of interest:

server/opennicsystem.cpp:252

/**
  * @brief Add a dns entry to the system's list of DNS resolvers.
  * @param resolver The IP address of the resolver to add to the system
  * @param index resolver sequence (1..n)
  */
int OpenNICSystem::updateResolver(QHostAddress& resolver,int index,QString& output)
{
...
}


This method spins up an external process called "netsh" and passes all the arguments on the command line. Yeah, I would like to make this better handle these situations on WIndows(tm).

You probably have to change "Local Area Connection" to whatever the name of your WiFi connection is.

Next time I spend some time on OpenNIC Wizard I will try to make this behave better, or at least make it easy to over-ride the device name.

**Comment by 8bitgeek** [comment]
A permanent fix for this will be incorporated in the next build.

**Comment by 8bitgeek** [comment]
See this issue https://github.com/8bitgeek/OpenNIC-Wizard/issues/9
